# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 00:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('json_graph', django.contrib.postgres.fields.jsonb.JSONField()),
                ('density', models.FloatField()),
                ('path_length', models.FloatField()),
                ('edge_connectivity', models.FloatField()),
                ('node_connectivity', models.FloatField()),
                ('analysed_channels', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('graph_type', models.CharField(choices=[('subscription', 'subscription'), ('mention', 'mention')], default='subscription', max_length=12)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Archive')),
            ],
        ),
    ]
