# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallmetrics',
            name='average_clustering',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
