# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_overallmetrics_average_clustering'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallmetrics',
            name='public_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
