# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded',),
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='archives.Archive')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_mentions', models.IntegerField(default=0)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention', to='archives.Archive')),
                ('mention_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention', to='archives.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('ts', models.DateTimeField()),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='archives.Archive')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='archives.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_id', models.CharField(max_length=10)),
                ('team_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=100)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_users', to='archives.Archive')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='message',
            name='slack_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='archives.SlackUser'),
        ),
        migrations.AddField(
            model_name='mention',
            name='mention_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention_receiver', to='archives.SlackUser'),
        ),
        migrations.AddField(
            model_name='mention',
            name='mention_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention_sender', to='archives.SlackUser'),
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='member', to='archives.SlackUser'),
        ),
    ]
