# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='slackuser',
        ),
        migrations.AlterField(
            model_name='archive',
            name='uploaded',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 23, 8, 26, 918148)),
        ),
    ]
