# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20171124_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='uploaded',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 25, 15, 17, 15, 743338)),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='archives.Channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='slackuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='archives.SlackUser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
    ]
