# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_auto_20171130_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='owner',
            new_name='user',
        ),
    ]
